"""initial_schema

Revision ID: 0ef8a817f493
Revises: 
Create Date: 2026-06-23 17:28:47.320419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ef8a817f493'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accumulation_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('rs_30', sa.Float(), nullable=False),
    sa.Column('rs_90', sa.Float(), nullable=False),
    sa.Column('rs_180', sa.Float(), nullable=False),
    sa.Column('quality_pillar', sa.Integer(), nullable=True),
    sa.Column('growth_pillar', sa.Integer(), nullable=True),
    sa.Column('valuation_pillar', sa.Integer(), nullable=True),
    sa.Column('rs_pillar', sa.Integer(), nullable=True),
    sa.Column('cagr_eps_3y', sa.Float(), nullable=True),
    sa.Column('cagr_eps_5y', sa.Float(), nullable=True),
    sa.Column('valuation_pillar_pct', sa.Float(), nullable=False),
    sa.Column('thesis_text', sa.String(), nullable=False),
    sa.Column('hard_avoid_active', sa.Boolean(), nullable=False),
    sa.Column('hard_avoid_reasons_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accumulation_candidate_run_id'), 'accumulation_candidate', ['run_id'], unique=False)
    op.create_index(op.f('ix_accumulation_candidate_symbol'), 'accumulation_candidate', ['symbol'], unique=False)
    op.create_table('accumulation_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qty_total', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('last_thesis_check_at', sa.DateTime(), nullable=False),
    sa.Column('paused_reason', sa.String(length=256), nullable=True),
    sa.CheckConstraint("state IN ('BUILDING','FULL','PAUSED','EXITED','CONVERTED_TO_SWING')", name='ck_accum_state'),
    sa.CheckConstraint('qty_total >= 0', name='ck_accum_qty_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accumulation_position_symbol'), 'accumulation_position', ['symbol'], unique=True)
    op.create_table('alert_cooldown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('SL_BREACH','SL_WARNING','T1_HIT','NO_PROGRESS')", name='ck_cooldown_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_cooldown_symbol'), 'alert_cooldown', ['symbol'], unique=False)
    op.create_table('bundle_stat_per_regime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle', sa.String(length=32), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('oos_sharpe_shrunk', sa.Float(), nullable=False),
    sa.Column('oos_expectancy_R', sa.Float(), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.CheckConstraint('oos_sharpe_shrunk BETWEEN -3 AND 3', name='ck_bundle_stat_sharpe_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle', 'regime', 'as_of_date')
    )
    op.create_index(op.f('ix_bundle_stat_per_regime_as_of_date'), 'bundle_stat_per_regime', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_bundle_stat_per_regime_bundle'), 'bundle_stat_per_regime', ['bundle'], unique=False)
    op.create_index(op.f('ix_bundle_stat_per_regime_regime'), 'bundle_stat_per_regime', ['regime'], unique=False)
    op.create_table('calibration_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('n_closed', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('expectancy_R', sa.Float(), nullable=False),
    sa.Column('ci_low_R', sa.Float(), nullable=False),
    sa.Column('ci_high_R', sa.Float(), nullable=False),
    sa.Column('sprt_state', sa.String(length=16), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('confidence_band', sa.String(length=8), nullable=False),
    sa.CheckConstraint("confidence_band IN ('low','medium','high')", name='ck_calib_band'),
    sa.CheckConstraint("sprt_state IN ('accept_H0','accept_H1','continue')", name='ck_calib_sprt'),
    sa.CheckConstraint('"ci_low_R" <= "expectancy_R" AND "expectancy_R" <= "ci_high_R"', name='ck_calib_ci_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_row_bucket'), 'calibration_row', ['bucket'], unique=False)
    op.create_index(op.f('ix_calibration_row_regime'), 'calibration_row', ['regime'], unique=False)
    op.create_table('cost_model_run',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('drawdown_governor_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('pool_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('high_water_mark', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('consecutive_recovery_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawdown_governor_state_as_of_date'), 'drawdown_governor_state', ['as_of_date'], unique=True)
    op.create_table('latest_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latest_price_symbol'), 'latest_price', ['symbol'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('SL_PROXIMITY','PNL_UPDATE','T1_PROXIMITY','PRICE_ALERT','SL_BREACH')", name='ck_notification_kind'),
    sa.CheckConstraint("severity IN ('INFO','WARNING','URGENT')", name='ck_notification_severity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_kind'), 'notification', ['kind'], unique=False)
    op.create_table('regime_snapshot',
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('nifty_close', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pct_above_50dma', sa.Float(), nullable=False),
    sa.Column('pct_above_200dma', sa.Float(), nullable=False),
    sa.Column('advance_decline', sa.Float(), nullable=False),
    sa.Column('india_vix', sa.Float(), nullable=False),
    sa.Column('fii_flow_inr', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('dii_flow_inr', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('breadth_confirmed_flip', sa.Boolean(), nullable=False),
    sa.CheckConstraint("label IN ('BULL','BEAR','SIDEWAYS')", name='ck_regime_label'),
    sa.PrimaryKeyConstraint('as_of_date')
    )
    op.create_table('run_log',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('job_name', sa.String(length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_run_log_job_name'), 'run_log', ['job_name'], unique=False)
    op.create_table('swing_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('bundle', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('entry', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_1', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_2', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expectancy_R', sa.Float(), nullable=False),
    sa.Column('drawn_rr', sa.Float(), nullable=False),
    sa.Column('regime_at_signal', sa.String(length=16), nullable=False),
    sa.Column('pillar_breakdown_json', sa.JSON(), nullable=False),
    sa.Column('counterfactual_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("label IN ('BUY','BUY_WATCH','WATCH','HOLD','AVOID')", name='ck_swing_signal_label'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swing_signal_run_id'), 'swing_signal', ['run_id'], unique=False)
    op.create_index(op.f('ix_swing_signal_symbol'), 'swing_signal', ['symbol'], unique=False)
    op.create_table('universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('median_traded_value_inr', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('free_float_mcap_inr', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('is_fno_listed', sa.Boolean(), nullable=False),
    sa.Column('in_universe', sa.Boolean(), nullable=False),
    sa.CheckConstraint('median_traded_value_inr >= 0', name='ck_universe_mtv_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of_date')
    )
    op.create_index(op.f('ix_universe_as_of_date'), 'universe', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_universe_symbol'), 'universe', ['symbol'], unique=False)
    op.create_table('walk_forward_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('bundle', sa.String(length=32), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('step_days', sa.Integer(), nullable=False),
    sa.Column('is_sharpe_median', sa.Float(), nullable=False),
    sa.Column('oos_sharpe_median', sa.Float(), nullable=False),
    sa.Column('overfit_flag', sa.Boolean(), nullable=False),
    sa.Column('windows_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walk_forward_run_symbol'), 'walk_forward_run', ['symbol'], unique=False)
    op.create_table('weekly_postmortem',
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('swing_return_pct', sa.Float(), nullable=False),
    sa.Column('nifty_return_pct', sa.Float(), nullable=False),
    sa.Column('regime_switched_return_pct', sa.Float(), nullable=False),
    sa.Column('random_baseline_return_pct', sa.Float(), nullable=False),
    sa.Column('n_swing_trades_closed', sa.Integer(), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.Column('report_md_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('week_ending')
    )
    op.create_table('swing_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('bundle', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('risk_R', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('realized_R', sa.Float(), nullable=True),
    sa.Column('mfe_R', sa.Float(), nullable=True),
    sa.Column('mae_R', sa.Float(), nullable=True),
    sa.CheckConstraint("state IN ('OPEN','T1_HIT','CLOSED_WIN','CLOSED_LOSS','SCRATCHED','EXPIRED')", name='ck_swing_trade_state'),
    sa.CheckConstraint('state NOT IN (\'CLOSED_WIN\',\'CLOSED_LOSS\') OR (closed_at IS NOT NULL AND "realized_R" IS NOT NULL)', name='ck_swing_trade_close_requires_fields'),
    sa.ForeignKeyConstraint(['signal_id'], ['swing_signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swing_trade_symbol'), 'swing_trade', ['symbol'], unique=False)
    op.create_table('tranche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('atr_normalized_trigger_pct', sa.Float(), nullable=False),
    sa.Column('filled_at_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('thesis_revalidated', sa.Boolean(), nullable=False),
    sa.CheckConstraint('seq BETWEEN 1 AND 5', name='ck_tranche_seq'),
    sa.ForeignKeyConstraint(['position_id'], ['accumulation_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('MOCK','REAL')", name='ck_fill_kind'),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_fill_side'),
    sa.ForeignKeyConstraint(['trade_id'], ['swing_trade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop legacy v1 tables (CASCADE handles FK constraints between them)
    _v1_tables = [
        'mock_portfolios', 'market_regime_snapshots', 'trading_params',
        'recommendations', 'backtest_results', 'trade_outcomes_audit',
        'alerts', 'watchlist', 'tuning_suggestions', 'paper_trades',
        'tuning_history', 'walk_forward_runs', 'news_events',
        'weekly_runs', 'rejected_headlines',
    ]
    for _t in _v1_tables:
        op.execute(f'DROP TABLE IF EXISTS "{_t}" CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_headlines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('headline', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('filter_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rejected_headlines_pkey'))
    )
    op.create_index(op.f('ix_rejected_headlines_symbol'), 'rejected_headlines', ['symbol'], unique=False)
    op.create_index(op.f('idx_rejected_symbol_at'), 'rejected_headlines', ['symbol', 'rejected_at'], unique=False)
    op.create_table('weekly_runs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('weekly_runs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('market_regime', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nifty_trend', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('strategy_selected', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('stocks_screened', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stocks_analysed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_buy_signals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_watch_signals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_md_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('run_type', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('params_version_id', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='weekly_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('news_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('headline', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_material', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alert_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('material_event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('news_events_pkey'))
    )
    op.create_index(op.f('ix_news_events_symbol'), 'news_events', ['symbol'], unique=False)
    op.create_table('walk_forward_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('bundle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('window_idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('oos_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('oos_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_sharpe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_sharpe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oos_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oos_win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overfit_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('walk_forward_runs_pkey'))
    )
    op.create_index(op.f('ix_walk_forward_runs_symbol'), 'walk_forward_runs', ['symbol'], unique=False)
    op.create_index(op.f('ix_walk_forward_runs_run_date'), 'walk_forward_runs', ['run_date'], unique=False)
    op.create_index(op.f('ix_walk_forward_runs_bundle_name'), 'walk_forward_runs', ['bundle_name'], unique=False)
    op.create_index(op.f('idx_wfr_symbol_bundle_date'), 'walk_forward_runs', ['symbol', 'bundle_name', 'run_date'], unique=False)
    op.create_table('tuning_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suggestion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('dimension', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('dimension_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('change_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('win_rate_before', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('win_rate_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rollback_after', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['tuning_suggestions.id'], name=op.f('tuning_history_suggestion_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tuning_history_pkey'))
    )
    op.create_index(op.f('ix_tuning_history_suggestion_id'), 'tuning_history', ['suggestion_id'], unique=False)
    op.create_index(op.f('idx_th_suggestion'), 'tuning_history', ['suggestion_id'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('paper_trades_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('linked_recommendation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('direction', postgresql.ENUM('LONG', 'SHORT', name='tradedirection'), autoincrement=False, nullable=True),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('entry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capital_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('realised_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('realised_pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('strategy_used', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', name='tradestatus'), autoincrement=False, nullable=True),
    sa.Column('exit_reason', postgresql.ENUM('TARGET1', 'TARGET2', 'STOP', 'MANUAL', 'SIGNAL', 'EXPIRED', name='tradeexitreason'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['linked_recommendation_id'], ['recommendations.id'], name='paper_trades_linked_recommendation_id_fkey'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['mock_portfolios.id'], name='paper_trades_portfolio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paper_trades_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_paper_trades_status'), 'paper_trades', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trades_portfolio_id'), 'paper_trades', ['portfolio_id'], unique=False)
    op.create_table('tuning_suggestions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('dimension_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target_win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('n_trades', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('suggestion_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tuning_suggestions_pkey'))
    )
    op.create_index(op.f('ix_tuning_suggestions_report_date'), 'tuning_suggestions', ['report_date'], unique=False)
    op.create_index(op.f('ix_tuning_suggestions_dimension'), 'tuning_suggestions', ['dimension'], unique=False)
    op.create_index(op.f('idx_ts_dimension_date'), 'tuning_suggestions', ['dimension', 'report_date'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('watchlist_pkey')),
    sa.UniqueConstraint('symbol', name=op.f('watchlist_symbol_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('alert_type', postgresql.ENUM('PRE_SL_WARNING', 'TARGET1_HIT', 'TARGET2_HIT', 'TREND_INVALIDATED', name='alerttype'), autoincrement=False, nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channels_sent', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('acknowledged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('ltp_at_trigger', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['mock_portfolios.id'], name=op.f('alerts_portfolio_id_fkey')),
    sa.ForeignKeyConstraint(['trade_id'], ['paper_trades.id'], name=op.f('alerts_trade_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_trade_id'), 'alerts', ['trade_id'], unique=False)
    op.create_index(op.f('ix_alerts_portfolio_id'), 'alerts', ['portfolio_id'], unique=False)
    op.create_index(op.f('idx_alerts_trade_type_time'), 'alerts', ['trade_id', 'alert_type', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_index(op.f('idx_alerts_portfolio_time'), 'alerts', ['portfolio_id', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_table('trade_outcomes_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('outcome', postgresql.ENUM('HIT_T1', 'HIT_T2', 'STOPPED', 'EXPIRED', 'PENDING', name='outcomeverdict'), autoincrement=False, nullable=False),
    sa.Column('outcome_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mfe_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mae_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trading_days_held', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_bucket', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('bundle_used', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('regime_at_signal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('trade_outcomes_audit_recommendation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_outcomes_audit_pkey'))
    )
    op.create_index(op.f('ix_trade_outcomes_audit_symbol'), 'trade_outcomes_audit', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_audit_score_bucket'), 'trade_outcomes_audit', ['score_bucket'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_audit_recommendation_id'), 'trade_outcomes_audit', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_audit_outcome'), 'trade_outcomes_audit', ['outcome'], unique=False)
    op.create_index(op.f('idx_toa_symbol'), 'trade_outcomes_audit', ['symbol'], unique=False)
    op.create_index(op.f('idx_toa_score_bucket'), 'trade_outcomes_audit', ['score_bucket'], unique=False)
    op.create_index(op.f('idx_toa_recommendation'), 'trade_outcomes_audit', ['recommendation_id'], unique=False)
    op.create_index(op.f('idx_toa_outcome'), 'trade_outcomes_audit', ['outcome'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bundle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_return_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_drawdown_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_assigned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('equity_curve_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weekly_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=20), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['weekly_run_id'], ['weekly_runs.id'], name=op.f('backtest_results_weekly_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('backtest_results_pkey'))
    )
    op.create_index(op.f('idx_backtest_results_bundle_date'), 'backtest_results', ['bundle_name', 'run_date'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weekly_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('recommendation', postgresql.ENUM('BUY', 'SELL', 'HOLD', 'WATCH', 'AVOID', name='recommendationverdict'), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_mid', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('target1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rr_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hold_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hold_days_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hold_days_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strategy_used', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('technical_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('smart_money_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reasoning_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_on_demand', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('outcome', postgresql.ENUM('HIT_T1', 'HIT_T2', 'STOPPED', 'EXPIRED', 'PENDING', name='outcomeverdict'), autoincrement=False, nullable=True),
    sa.Column('outcome_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('outcome_fill_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('outcome_exit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('outcome_exit_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('outcome_tracked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revalidation_note', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('revalidated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('regime_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rr_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mfe_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mae_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['weekly_run_id'], ['weekly_runs.id'], name=op.f('recommendations_weekly_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendations_pkey'))
    )
    op.create_index(op.f('ix_recommendations_symbol'), 'recommendations', ['symbol'], unique=False)
    op.create_index(op.f('ix_recommendations_outcome'), 'recommendations', ['outcome'], unique=False)
    op.create_table('trading_params',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('param_key', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value_type', sa.VARCHAR(length=10), server_default=sa.text("'float'::character varying"), autoincrement=False, nullable=False),
    sa.Column('min_allowed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_allowed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trading_params_pkey')),
    sa.UniqueConstraint('param_key', name=op.f('trading_params_param_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_trading_params_param_key'), 'trading_params', ['param_key'], unique=False)
    op.create_index(op.f('idx_trading_params_key'), 'trading_params', ['param_key'], unique=False)
    op.create_table('market_regime_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('nifty_trend', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nifty_slope', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_from_ema50_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sector_rs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('market_regime_snapshots_pkey')),
    sa.UniqueConstraint('snapshot_date', name=op.f('market_regime_snapshots_snapshot_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_market_regime_snapshots_snapshot_date'), 'market_regime_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('idx_regime_snapshots_date'), 'market_regime_snapshots', ['snapshot_date'], unique=False)
    op.create_table('mock_portfolios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mock_portfolios_pkey')),
    sa.UniqueConstraint('name', name=op.f('mock_portfolios_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('fill')
    op.drop_table('tranche')
    op.drop_index(op.f('ix_swing_trade_symbol'), table_name='swing_trade')
    op.drop_table('swing_trade')
    op.drop_table('weekly_postmortem')
    op.drop_index(op.f('ix_walk_forward_run_symbol'), table_name='walk_forward_run')
    op.drop_table('walk_forward_run')
    op.drop_index(op.f('ix_universe_symbol'), table_name='universe')
    op.drop_index(op.f('ix_universe_as_of_date'), table_name='universe')
    op.drop_table('universe')
    op.drop_index(op.f('ix_swing_signal_symbol'), table_name='swing_signal')
    op.drop_index(op.f('ix_swing_signal_run_id'), table_name='swing_signal')
    op.drop_table('swing_signal')
    op.drop_index(op.f('ix_run_log_job_name'), table_name='run_log')
    op.drop_table('run_log')
    op.drop_table('regime_snapshot')
    op.drop_index(op.f('ix_notification_kind'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_latest_price_symbol'), table_name='latest_price')
    op.drop_table('latest_price')
    op.drop_index(op.f('ix_drawdown_governor_state_as_of_date'), table_name='drawdown_governor_state')
    op.drop_table('drawdown_governor_state')
    op.drop_table('cost_model_run')
    op.drop_index(op.f('ix_calibration_row_regime'), table_name='calibration_row')
    op.drop_index(op.f('ix_calibration_row_bucket'), table_name='calibration_row')
    op.drop_table('calibration_row')
    op.drop_index(op.f('ix_bundle_stat_per_regime_regime'), table_name='bundle_stat_per_regime')
    op.drop_index(op.f('ix_bundle_stat_per_regime_bundle'), table_name='bundle_stat_per_regime')
    op.drop_index(op.f('ix_bundle_stat_per_regime_as_of_date'), table_name='bundle_stat_per_regime')
    op.drop_table('bundle_stat_per_regime')
    op.drop_index(op.f('ix_alert_cooldown_symbol'), table_name='alert_cooldown')
    op.drop_table('alert_cooldown')
    op.drop_index(op.f('ix_accumulation_position_symbol'), table_name='accumulation_position')
    op.drop_table('accumulation_position')
    op.drop_index(op.f('ix_accumulation_candidate_symbol'), table_name='accumulation_candidate')
    op.drop_index(op.f('ix_accumulation_candidate_run_id'), table_name='accumulation_candidate')
    op.drop_table('accumulation_candidate')
    # ### end Alembic commands ###
