import { useState } from 'react'

const TERMS = [
  // Market & regime
  { term: 'Regime', def: 'Current market condition — BULL, BEAR, or SIDEWAYS — derived from Nifty 500 breadth (% above 50/200 DMA), advance-decline ratio, India VIX, and FII/DII flow.' },
  { term: 'Breadth', def: 'The percentage of NSE 500 stocks trading above their 50-day or 200-day moving average. A proxy for market participation — high breadth = healthy uptrend, low breadth = weak/deteriorating market.' },
  { term: 'FII / DII', def: 'Foreign Institutional Investor / Domestic Institutional Investor. Their daily net buy/sell flows are a regime input. Sustained FII selling into a rally is a bearish signal.' },
  { term: 'India VIX', def: 'India\'s volatility index, measuring implied volatility in Nifty options. Values above ~20 indicate elevated fear; above ~25 often precede sharp drawdowns.' },
  { term: 'Advance-Decline', def: 'Daily count of advancing stocks minus declining stocks on NSE. A broad rally with weak A/D is a breadth divergence — often precedes a reversal.' },

  // Signals & scoring
  { term: 'Signal', def: 'A trade recommendation generated by the Sunday pipeline for a specific symbol. Labels: BUY (enter long), SELL (exit or short), WATCH (on radar, no entry yet), EXIT (close existing position).' },
  { term: 'Bundle', def: 'A named strategy configuration — e.g. "trend_score_70_75". Signals always belong to one bundle, which tracks its own calibration and SPRT state independently.' },
  { term: 'Pillar score', def: 'A sub-score for one quality dimension of a signal. Six pillars: Technical (30pts), Expectancy (25pts), Flow (15pts), Regime fit (15pts), Fundamentals (10pts), Sentiment (5pts). Total = 100.' },
  { term: 'Calibration band', def: 'The score range bucket a signal falls in — e.g. "70–75". Each bucket has independently tracked win rate, expectancy, and SPRT state. Signals in high-confidence buckets carry more weight.' },
  { term: 'Counterfactual', def: 'The pipeline\'s explanation of what would need to be true for this signal to have been rated differently — used for post-trade learning and parameter tuning.' },

  // Risk & trade management
  { term: 'R:R', def: 'Risk:Reward ratio. Calculated as (Target − Entry) / (Entry − Stop Loss). The pipeline suppresses signals where R:R < 1.5.' },
  { term: 'R-multiple', def: 'A unit of return expressed as a multiple of initial risk. +1R = gained exactly what you risked. +2R = gained twice the risk. Expectancy is the average R-multiple across all closed trades.' },
  { term: 'Expectancy (R)', def: 'Average profit per trade in R-multiples: (win_rate × avg_win_R) − (loss_rate × avg_loss_R). A positive expectancy means the strategy has edge. The target threshold is +0.3R.' },
  { term: 'Entry', def: 'The pipeline\'s recommended entry price for a signal. Displayed as a green dashed line on the chart.' },
  { term: 'Stop Loss (SL)', def: 'The price level at which the trade thesis is invalidated and the position should be closed. Displayed as a red dashed line on the chart.' },
  { term: 'Target (T1 / T2)', def: 'The pipeline\'s profit targets. T1 is the primary target (where partial exits are often taken); T2 is the stretch target. Both are displayed as blue dashed lines on the chart.' },
  { term: 'SL Distance %', def: 'How far the current price is from the stop loss, expressed as a percentage. Used to monitor proximity to invalidation.' },
  { term: 'MAE', def: 'Maximum Adverse Excursion. The worst intra-trade drawdown from entry before the trade was closed. Used to calibrate stop placements.' },
  { term: 'MFE', def: 'Maximum Favourable Excursion. The best unrealised gain reached during the trade. Comparing MFE to final P&L reveals how much profit was "left on the table."' },

  // Accumulation
  { term: 'Tranche', def: 'A single buy order in an accumulation position. Positions are built over multiple tranches as the stock dips to re-entry levels — averaging down on quality.' },
  { term: 'Accumulation candidate', def: 'A high-quality stock identified by the Sunday pipeline as suitable for multi-tranche DCA. Scored 0–100 based on relative strength, fundamentals, and valuation.' },
  { term: 'Hard Avoid', def: 'A flag on an accumulation candidate indicating it fails a fundamental quality gate (e.g. negative ROE, excessive debt). Positions cannot be started while this flag is active.' },

  // Technical indicators
  { term: 'DMA', def: 'Daily Moving Average. The 20 DMA tracks short-term trend; 50 DMA tracks medium-term; 200 DMA tracks long-term. Shown as coloured lines on charts (blue/amber/red-dashed).' },
  { term: 'Golden Cross', def: 'When the 20-day DMA crosses above the 50-day DMA. A bullish trend initiation signal, marked with ✕ on charts when the GX overlay is enabled.' },
  { term: 'Bollinger Bands (BB)', def: 'Bands plotted 2 standard deviations above and below a 20-day moving average. Price near the upper band is overbought; near the lower band is oversold. The squeeze (narrow bands) precedes volatility expansion.' },
  { term: 'MACD', def: 'Moving Average Convergence Divergence. Plots the difference between 12 and 26 EMA (MACD line, blue) vs its 9-period signal line (amber). Histogram shows the gap between them — used to spot momentum shifts.' },
  { term: 'RS', def: 'Relative Strength. A stock\'s price return vs the Nifty 500 index over 30, 90, and 180 days. Expressed as a percentile rank — 80th means the stock outperformed 80% of the NSE 500 universe.' },

  // Statistical / system terms
  { term: 'SPRT', def: 'Sequential Probability Ratio Test. Continuously monitors each strategy bucket\'s win rate against null (no edge) and alternative (positive edge) hypotheses. States: accept_H1 (edge confirmed), accept_H0 (no edge), continue (still sampling).' },
  { term: 'Walk-forward', def: 'A backtesting methodology that trains on a rolling in-sample window and validates on the next out-of-sample period. Avoids look-ahead bias unlike standard backtests.' },
  { term: 'Deadzone', def: 'A calibrated price band around the entry point within which re-entry signals are suppressed. Prevents whipsaw re-entries after a stop-loss hit.' },
  { term: 'CMP', def: 'Current Market Price. The latest available price fetched live from Angel One or yfinance. Used to pre-fill trade entry forms.' },
  { term: 'Fill', def: 'A record of an actual trade execution — side (BUY/SELL), quantity, price, and timestamp. Each swing trade has one or more fills.' },
  { term: 'OHLCV', def: 'Open, High, Low, Close, Volume — the standard daily price bar data fetched from the provider and stored for charting and indicator calculation.' },
]

export default function Glossary() {
  const [search, setSearch] = useState('')
  const filtered = TERMS.filter(t =>
    t.term.toLowerCase().includes(search.toLowerCase()) ||
    t.def.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div className="flex flex-col gap-4 max-w-2xl">
      <div>
        <h1 className="text-xl font-semibold">Glossary</h1>
        <p className="text-sm mt-0.5" style={{ color: 'var(--muted)' }}>
          Key terms used in Plutus
        </p>
      </div>

      <input
        value={search}
        onChange={e => setSearch(e.target.value)}
        placeholder="Search terms…"
        style={{ background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text)' }}
        className="rounded-lg px-3 py-2 text-sm outline-none w-full"
      />

      <div className="flex flex-col gap-2">
        {filtered.map(({ term, def }) => (
          <div key={term}
               style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
               className="rounded-xl px-5 py-4">
            <div className="font-semibold text-sm mb-1" style={{ color: 'var(--blue)' }}>{term}</div>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--muted)' }}>{def}</p>
          </div>
        ))}
        {!filtered.length && (
          <p className="text-sm" style={{ color: 'var(--dim)' }}>No matching terms.</p>
        )}
      </div>
    </div>
  )
}
